cutadapt -O 3 -b AATGATACGGCGACCACCGAGATCTACACGTTCAGAGTTCTACAGTCCGA -a TGGAATTCTCGGGTGCCAAGGAACTCCAGTCACGTAGAGATCTCGTATGCCGTCTTCTGCTTG 7313_Nsunrescue_empty1.fq.gz -q 20 -m 5 > 7313_Nsunrescue_empty1_trimmed.fq

cutadapt -O 3 -b AATGATACGGCGACCACCGAGATCTACACGTTCAGAGTTCTACAGTCCGA -a TGGAATTCTCGGGTGCCAAGGAACTCCAGTCACGTCCGCATCTCGTATGCCGTCTTCTGCTTG 7313_Nsunrescue_empty2.fq.gz -q 20 -m 5 > 7313_Nsunrescue_empty2_trimmed.fq

cutadapt -O 3 -b AATGATACGGCGACCACCGAGATCTACACGTTCAGAGTTCTACAGTCCGA -a TGGAATTCTCGGGTGCCAAGGAACTCCAGTCACGTGAAAATCTCGTATGCCGTCTTCTGCTTG 7313_Nsunrescue_empty3.fq.gz -q 20 -m 5 > 7313_Nsunrescue_empty3_trimmed.fq

cutadapt -O 3 -b AATGATACGGCGACCACCGAGATCTACACGTTCAGAGTTCTACAGTCCGA -a TGGAATTCTCGGGTGCCAAGGAACTCCAGTCACGTGGCCATCTCGTATGCCGTCTTCTGCTTG 7313_Nsunrescue_empty4.fq.gz -q 20 -m 5 > 7313_Nsunrescue_empty4_trimmed.fq

cutadapt -O 3 -b AATGATACGGCGACCACCGAGATCTACACGTTCAGAGTTCTACAGTCCGA -a TGGAATTCTCGGGTGCCAAGGAACTCCAGTCACGTTTCGATCTCGTATGCCGTCTTCTGCTTG 7314_Nsunrescue_wt1.fq.gz -q 20 -m 5 > 7314_Nsunrescue_wt1_trimmed.fq

cutadapt -O 3 -b AATGATACGGCGACCACCGAGATCTACACGTTCAGAGTTCTACAGTCCGA -a TGGAATTCTCGGGTGCCAAGGAACTCCAGTCACCGTACGATCTCGTATGCCGTCTTCTGCTTG 7314_Nsunrescue_wt2.fq.gz -q 20 -m 5 > 7314_Nsunrescue_wt2_trimmed.fq

cutadapt -O 3 -b AATGATACGGCGACCACCGAGATCTACACGTTCAGAGTTCTACAGTCCGA -a TGGAATTCTCGGGTGCCAAGGAACTCCAGTCACGAGTGGATCTCGTATGCCGTCTTCTGCTTG 7314_Nsunrescue_wt3.fq.gz -q 20 -m 5 > 7314_Nsunrescue_wt3_trimmed.fq

cutadapt -O 3 -b AATGATACGGCGACCACCGAGATCTACACGTTCAGAGTTCTACAGTCCGA -a TGGAATTCTCGGGTGCCAAGGAACTCCAGTCACGGTAGCATCTCGTATGCCGTCTTCTGCTTG 7314_Nsunrescue_wt4.fq.gz -q 20 -m 5 > 7314_Nsunrescue_wt4_trimmed.fq

cutadapt -O 3 -b AATGATACGGCGACCACCGAGATCTACACGTTCAGAGTTCTACAGTCCGA -a TGGAATTCTCGGGTGCCAAGGAACTCCAGTCACACAGTGATCTCGTATGCCGTCTTCTGCTTG 7315_Nsunrescue_c321a1_2.fq.gz -q 20 -m 5 > 7315_Nsunrescue_c321a1_2_trimmed.fq

cutadapt -O 3 -b AATGATACGGCGACCACCGAGATCTACACGTTCAGAGTTCTACAGTCCGA -a TGGAATTCTCGGGTGCCAAGGAACTCCAGTCACGCCAATATCTCGTATGCCGTCTTCTGCTTG 7315_Nsunrescue_c321a2_2.fq.gz -q 20 -m 5 > 7315_Nsunrescue_c321a2_2_trimmed.fq

cutadapt -O 3 -b AATGATACGGCGACCACCGAGATCTACACGTTCAGAGTTCTACAGTCCGA -a TGGAATTCTCGGGTGCCAAGGAACTCCAGTCACCAGATCATCTCGTATGCCGTCTTCTGCTTG 7315_Nsunrescue_c321a3_2.fq.gz -q 20 -m 5 > 7315_Nsunrescue_c321a3_2_trimmed.fq

cutadapt -O 3 -b AATGATACGGCGACCACCGAGATCTACACGTTCAGAGTTCTACAGTCCGA -a TGGAATTCTCGGGTGCCAAGGAACTCCAGTCACACTTGAATCTCGTATGCCGTCTTCTGCTTG 7315_Nsunrescue_c321a4_2.fq.gz -q 20 -m 5 > 7315_Nsunrescue_c321a4_2_trimmed.fq

cutadapt -O 3 -b AATGATACGGCGACCACCGAGATCTACACGTTCAGAGTTCTACAGTCCGA -a TGGAATTCTCGGGTGCCAAGGAACTCCAGTCACGTAGAGATCTCGTATGCCGTCTTCTGCTTG 7315_Nsunrescue_c321a1_1.fq.gz -q 20 -m 5 > 7315_Nsunrescue_c321a1_1_trimmed.fq

cutadapt -O 3 -b AATGATACGGCGACCACCGAGATCTACACGTTCAGAGTTCTACAGTCCGA -a TGGAATTCTCGGGTGCCAAGGAACTCCAGTCACGTCCGCATCTCGTATGCCGTCTTCTGCTTG 7315_Nsunrescue_c321a2_1.fq.gz -q 20 -m 5 > 7315_Nsunrescue_c321a2_1_trimmed.fq

cutadapt -O 3 -b AATGATACGGCGACCACCGAGATCTACACGTTCAGAGTTCTACAGTCCGA -a TGGAATTCTCGGGTGCCAAGGAACTCCAGTCACGTGAAAATCTCGTATGCCGTCTTCTGCTTG 7315_Nsunrescue_c321a3_1.fq.gz -q 20 -m 5 > 7315_Nsunrescue_c321a3_1_trimmed.fq

cutadapt -O 3 -b AATGATACGGCGACCACCGAGATCTACACGTTCAGAGTTCTACAGTCCGA -a TGGAATTCTCGGGTGCCAAGGAACTCCAGTCACGTGGCCATCTCGTATGCCGTCTTCTGCTTG 7315_Nsunrescue_c321a4_1.fq.gz -q 20 -m 5 > 7315_Nsunrescue_c321a4_1_trimmed.fq

cutadapt -O 3 -b AATGATACGGCGACCACCGAGATCTACACGTTCAGAGTTCTACAGTCCGA -a TGGAATTCTCGGGTGCCAAGGAACTCCAGTCACATCACGATCTCGTATGCCGTCTTCTGCTTG 7316_Nsunrescue_c271a1_2.fq.gz -q 20 -m 5 > 7316_Nsunrescue_c271a1_2_trimmed.fq

cutadapt -O 3 -b AATGATACGGCGACCACCGAGATCTACACGTTCAGAGTTCTACAGTCCGA -a TGGAATTCTCGGGTGCCAAGGAACTCCAGTCACCGATGTATCTCGTATGCCGTCTTCTGCTTG 7316_Nsunrescue_c271a2_2.fq.gz -q 20 -m 5 > 7316_Nsunrescue_c271a2_2_trimmed.fq

cutadapt -O 3 -b AATGATACGGCGACCACCGAGATCTACACGTTCAGAGTTCTACAGTCCGA -a TGGAATTCTCGGGTGCCAAGGAACTCCAGTCACTGACCAATCTCGTATGCCGTCTTCTGCTTG 7316_Nsunrescue_c271a3_2.fq.gz -q 20 -m 5 > 7316_Nsunrescue_c271a3_2_trimmed.fq

cutadapt -O 3 -b AATGATACGGCGACCACCGAGATCTACACGTTCAGAGTTCTACAGTCCGA -a TGGAATTCTCGGGTGCCAAGGAACTCCAGTCACAGTCAAATCTCGTATGCCGTCTTCTGCTTG 7316_Nsunrescue_c271a1_1.fq.gz -q 20 -m 5 > 7316_Nsunrescue_c271a1_1_trimmed.fq

cutadapt -O 3 -b AATGATACGGCGACCACCGAGATCTACACGTTCAGAGTTCTACAGTCCGA -a TGGAATTCTCGGGTGCCAAGGAACTCCAGTCACAGTTCCATCTCGTATGCCGTCTTCTGCTTG 7316_Nsunrescue_c271a2_1.fq.gz -q 20 -m 5 > 7316_Nsunrescue_c271a2_1_trimmed.fq

cutadapt -O 3 -b AATGATACGGCGACCACCGAGATCTACACGTTCAGAGTTCTACAGTCCGA -a TGGAATTCTCGGGTGCCAAGGAACTCCAGTCACCCGTCCATCTCGTATGCCGTCTTCTGCTTG 7316_Nsunrescue_c271a3_1.fq.gz -q 20 -m 5 > 7316_Nsunrescue_c271a3_1_trimmed.fq

#run qc
PATH=$PATH:/home/ja313/software/fastqc ; export PATH
fastqc *trimmed.fq
mkdir trimqc
mv *fastqc* trimqc
